name: Build and test badger

on:
  pull_request:
    branches:
    - develop
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Check out PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.pull_request.head.sha }}
      - name: Check out branch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
      - uses: actions/checkout@v3
      - name: Install NPM
        run: npm install
      - name: Build and test
        run: |
          npm run build
  tryout:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.pull_request.head.sha }}
      - name: Check out branch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
      - name: Generate green badge
        uses: centipod/badger@master
        with:
          branch: ${{ github.base_ref }}
          directory: .badges
          label: 'Version'
          value: 'v1.0'
          status: true

      - name: Generate red badge
        uses: centipod/badger@master
        with:
          branch: ${{ github.base_ref }}
          directory: .badges
          label: 'Release'
          value: 'failed'
          status: false