name: Test badger

on:
  pull_request:
    branches:
      master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm run test
  tryout:
    runs-on: ubuntu-latest
    permissions: write-all
      - uses: actions/checkout@v3

      - name: Generate green badge
        uses: centipod/badger@master
        with:
          directory: .badges
          label: 'Version'
          value: 'v1.0'
          status: true

      - name: Generate red badge
        uses: centipod/badger@master
        with:
          directory: .badges
          label: 'Release'
          value: 'failed'
          status: false