name: Build distribution

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FMBOT_PAT }}

      - name: Display checked out files
        run: ls -lsa ${{ github.workspace }}

      - name: Clone Maven settings
        run: |
          cp -Rf ${{ github.workspace }}/.github/.m2 ~/.m2
          cp -Rf ${{ github.workspace }}/.github/.mvn ~/.mvn

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and test with Apache Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          GITHUB_TOKEN: ${{ secrets.FMBOT_PAT }}
          TEST_HOME: ${{ github.workspace }}